# Generated by Django 4.0.4 on 2022-05-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descrption',
            new_name='descripcion',
        ),
    ]
